dotenv: .env
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
wallets:
  from_key: ${PRIVATE_KEY}